language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install --dev --no-interaction --prefer-source

script:
  - vendor/bin/php-cs-fixer fix -v --dry-run src/
  - vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
